### ISSUE TITLE
Incorrect Link for Pretrained Model of Zinc250k

### ISSUE THREAD

**Issue by dbsxodud-11** [sail-sg/GDPO#2]
Hello,

I hope this message finds you well. I've encountered an issue with the provided Google Drive link that is supposed to direct me to the zinc250k pre-trained model. Instead of leading to the intended model, the link redirects to the pre-trained model for planar. Could the correct link to the zinc250k pre-trained model be provided?

I appreciate the work you're doing and look forward to a resolution!!
Best regards,
Taeyoung

**Comment by zyplanet** [comment]
We have updated the link, thanks for your reminding.
